"""empty message

Revision ID: 494aa27ef186
Revises: 
Create Date: 2023-03-22 14:32:21.652561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '494aa27ef186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('user_info')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course'], ['course_code'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('status')
        batch_op.drop_column('course')

    op.create_table('user_info',
    sa.Column('puid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('courseids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True)
    )
    op.create_table('course',
    sa.Column('courseid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('course_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('course_color', postgresql.ENUM('RED', 'ORANGE', 'YELLOW', 'GREEN', 'BLUE', 'CYAN', 'PINK', 'PURPLE', name='color'), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
