"""empty message

Revision ID: 268b3b8aedda
Revises: 35c0fe253b38
Create Date: 2023-03-22 17:13:55.498251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '268b3b8aedda'
down_revision = '35c0fe253b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
