"""empty message

Revision ID: 2b6ec30d7586
Revises: 263d80d3b9d6
Create Date: 2023-03-29 16:16:18.678904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6ec30d7586'
down_revision = '263d80d3b9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('netid', sa.String(), nullable=True))
        batch_op.drop_constraint('courses_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['netid'], ['netid'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('netid', sa.String(), nullable=False))
        batch_op.drop_constraint('users_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['netid'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_id_key', ['id'])
        batch_op.drop_column('netid')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('courses_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('netid')

    # ### end Alembic commands ###
