"""empty message

Revision ID: 5393c6d43766
Revises: 5b63b8113000
Create Date: 2023-03-29 18:07:35.568347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5393c6d43766'
down_revision = '5b63b8113000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=postgresql.ENUM('student', 'instructor', 'admin', name='role'),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['netid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('student', 'instructor', 'admin', name='role'),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
