"""empty message

Revision ID: 6d4787aeb4bc
Revises: 7bdddaaa3458
Create Date: 2023-03-22 17:48:35.606057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d4787aeb4bc'
down_revision = '7bdddaaa3458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=postgresql.ENUM('RED', 'ORANGE', 'YELLOW', 'GREEN', 'BLUE', 'CYAN', 'PINK', 'PURPLE', name='color'),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.String(),
               type_=postgresql.ENUM('RED', 'ORANGE', 'YELLOW', 'GREEN', 'BLUE', 'CYAN', 'PINK', 'PURPLE', name='color'),
               existing_nullable=True)

    # ### end Alembic commands ###
